# Generated by Django 5.2.6 on 2025-09-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('jersey', 'Jersey'), ('shoes', 'Shoes'), ('socks', 'Socks'), ('ball', 'Ball'), ('short', 'Short')], default='common', max_length=20),
        ),
    ]
